services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: jarvis_user
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: jarvis_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - jarvis_postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: jarvis_user
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: jarvis_test
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jarvis_user -d jarvis_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  jarvis_postgres_data:
    external: true
    name: ai-procjets_jarvis_postgres_data
  postgres_test_data:
